### ISSUE TITLE
Porting to Python3

### ISSUE THREAD

**Issue by ahmetax** [aalto-speech/flatcat#1]
Are you planning to port flatcat into Python3 also?

**Comment by Waino** [comment]
Morfessor FlatCat supports Python3.

Are you experiencing some particular error when running it under Python3? If you are, could you post the error message here?

**Comment by ahmetax** [comment]
I tried to install it by:

sudo pip3 install flatcat

Got the following message:

Collecting flatcat
   Could not find a version that satisfies the requirement flatcat (from 
versions: )
No matching distribution found for flatcat

**Comment by Waino** [comment]
FlatCat is not available for installing through pip.
To install, clone the github repository and use the included setup.py .
Installation instructions can be found at https://morfessor-flatcat.readthedocs.io/en/latest/installation.html#installation-instructions

**Comment by ahmetax** [comment]
Thank you. I installed FlatCat on Python3 as you described.
